### ISSUE TITLE
GitGutter not enabled by default regardless of config (OS X)

### ISSUE THREAD

**Issue by MaciekBaron** [airblade/vim-gitgutter#199]
Not sure if this is a case of [_PEBCAK_](http://en.wiktionary.org/wiki/PEBCAK) but I can't seem to be able to have GitGutter enabled by default when I open vim.

I am using vim 7.3 on OS X 10.8.4, I have installed the plugin using Vundle, my `.vimrc` config file has the following line:

```
let g:gitgutter_enabled = 1
```

However GitGutter is never enabled be default. It only starts working when I explicitly enable it using the `:GitGutterEnable` command (works fine afterwards). Weirdly the `g:gitgutter_sign_column_always` settings seems to be read and considered on load, not the "enabled" flag.

Am I doing something wrong or is there some sort of weird bug that appears on my setup?

**Comment by Signus** [comment]
To anybody who runs into this for OS X again, it's due to something (unsure of what) in the version of Vim supplied by Apple.

Initially vim-gitgutter would not work with vim 7.3:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jul  9 2015 23:58:42)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
```

I installed the latest from brew and switched out the symlink:

```bash
brew install vim
mv /usr/bin/vim /usr/bin/vim_OLD
ln -s /usr/local/Cellar/vim/7.4.1257/bin/vim /usr/bin/vim
```

And behold! vim-gitgutter is enabled automatically and starts displaying changes in the gutter immediately.
