### ISSUE TITLE
error spams when editing files as root

### ISSUE THREAD

**Issue by jldailey** [airblade/vim-gitgutter#222]
Error detected while processing function gitgutter#process_buffer..gitgutter#diff#run_diff..gitgutter#utility#file_relative_to_repo_root..gitgutter#utility#system:
line   10:
E484: Can't open file /tmp/vbltwha/2

I only enable gitgutter in my personal .vimrc, so it shouldn't even be enabled when running as root.

**Comment by airblade** [comment]
What does `:GitGutterDebug` produce?  And can you post your vimrc somewhere please?

Also could you confirm your vim-gitgutter is up to date?

**Comment by airblade** [comment]
Re running as root: vim-gitgutter will be enabled if it's installed and you haven't explicitly disabled it in the relevant vimrc.

Typically the E484 error means vim is having trouble executing external commands via `system()`.  Sometimes it's a permissions problem; sometimes it's because vim is being run under a non-POSIX shell.

**Comment by jldailey** [comment]
Yeah I'm using the (fairly new) fish shell, there is probably some weird interaction there.

I'll disable gitgutter explicitly in root's .vimrc... thanks for the quick response.

**Comment by jldailey** [comment]
Hmm that actually doesn't work, since "sudo vi foo" doesn't read root's .vimrc (not really sure why actually), but it appears to read the local user's .vimrc (maybe sudo preserves the current environment, including $HOME? not sure), but it still shows the error.

And the fish shell isn't the problem actually, because it works when running as the local user (root doesn't use fish as shell anyway).

Any chance this error could just be squelched?

**Comment by airblade** [comment]
That `vi foo` works but `sudo vi foo` doesn't seems to indicate some kind of environment difference.

In general vim offers no guarantees with the fish shell, especially with `system()` calls, because fish is non-POSIX.  If you pop `set shell=/bin/bash` in vimrc, does that make the error go away?

We don't want to squelch that error because it indicates a genuine problem preventing the plugin from running correctly.

**Comment by elken** [comment]
As someone else who was having this exact error, I can confirm adding setting `$shell` to a POSIX-compliant shell fixes it.

**Comment by airblade** [comment]
@elken Thanks for confirming.

I'm going to assume this is solved – but let me know if not.

**Comment by airblade** [comment]
@jldailey vim-gitgutter now supports the fish shell.
