### ISSUE TITLE
Not compatible with neovim

### ISSUE THREAD

**Issue by koddsson** [airblade/vim-gitgutter#229]
Adding vim-gitgutter as a plugin (using [neobundle](https://github.com/Shougo/neobundle.vim)) in neovim will result in a error when starting neovim.

```
☁  ~  nvim .nvimrc
Error detected while processing function gitgutter#highlight#define_signs..gitgutter#highlight#define_sign_text:
line    4:
E239: Invalid sign text: �~@�
Press ENTER or type command to continue
```

**Comment by airblade** [comment]
Could you try adding `scriptencoding utf-8` to the top of the file `autoload/gitgutter/highlight.vim` and let me know if it solves the problem?

**Comment by koddsson** [comment]
No change :(

```
diff --git a/autoload/gitgutter/highlight.vim b/autoload/gitgutter/highlight.vim
index f180acc..856180a 100644
--- a/autoload/gitgutter/highlight.vim
+++ b/autoload/gitgutter/highlight.vim
@@ -1,3 +1,5 @@
+scriptencoding utf-8
+
 function! gitgutter#highlight#define_sign_column_highlight()
   highlight default link SignColumn LineNr
 endfunction
```

**Comment by airblade** [comment]
Are you using the default signs or configuring them at all?  Are you using the latest vim-gitgutter?

**Comment by koddsson** [comment]
>Are you using the default signs or configuring them at all?

Not sure what that is so I think I'm just using the defaults :smile:

>Are you using the latest vim-gitgutter?

Yup. Or I'm on master with latest changes pulled.

```
☁  vim-gitgutter [master] ⚡ git pull origin master
From https://github.com/airblade/vim-gitgutter
 * branch            master     -> FETCH_HEAD
Already up-to-date.
☁  vim-gitgutter [master] ⚡
```

**Comment by airblade** [comment]
I've just updated to the latest neovim:

```sh
$ brew update
Updated Homebrew from 6e2238a5 to f15cffdb.
$ brew reinstall --HEAD neovim
$ nvim --version
NVIM 0.0.0-alpha+201502182054 (compiled Feb 19 2015 11:02:24)
Commit: b1d079c83b3dd459114d1ba7c2ff1b07a9ee3e9e
{blah blah blah}
```

When I fire it up, everything works fine including vim-gitgutter.

Weird.

Can you try adding this to your nvimrc?

```viml
let g:gitgutter_sign_removed_first_line = "^_"
```

**Comment by koddsson** [comment]
I reinstalled neovim to be sure and I have the same version as you.

Added that line into my `.nvimrc` and now it works! Will I experience any lack of usability with that variable set?

**Comment by airblade** [comment]
The problem is the text of the sign that's shown when you delete the top line(s) of a file.  By default this is an [overline](https://github.com/airblade/vim-gitgutter/blob/061258e04476c0f9f653a969e640bf03b3659594/plugin/gitgutter.vim#L40) which isn't an ASCII character; it's U+203E.  For some reason this is tripping up your neovim.

The workaround is to configure the sign's text as an ASCII character (or two), which you just did.  You won't experience any lack of usability.

Since we're using the same vim-gitgutter and the same neovim, and `scriptencoding utf-8` didn't fix the problem, I wonder whether the root problem is somewhere else.  Perhaps the font you use in neovim can't display the overline?  You could try typing the overline with `^K'-` (control-K apostrophe minus, without any spaces) and see what happens.

**Comment by koddsson** [comment]
Oh that's funny. Totally works in vim but displays a dash in neovim.

vim:
![screen shot 2015-02-19 at 10 38 02](https://cloud.githubusercontent.com/assets/318208/6265206/75399d56-b823-11e4-9bf7-35e0cc8f3be4.png)
neovim:
![screen shot 2015-02-19 at 10 38 15](https://cloud.githubusercontent.com/assets/318208/6265205/7539144e-b823-11e4-8912-ee5605ba05fc.png)

**Comment by koddsson** [comment]
I'll just keep that setting in my `.nvimrc`.

Thanks for the help and the awesome plugin! Wouldn't use neovim without it! :+1:

**Comment by airblade** [comment]
Thanks!  Glad you got it working :)
