### ISSUE TITLE
'[' mark (start of last change) is broken

### ISSUE THREAD

**Issue by petermehle** [airblade/vim-gitgutter#242]
I am using `` `[v`] `` (select text that was pasted/edited) all the time and I found broken for the last few weeks. If I disable git-gutter, it works, otherwise it doesn't. As I said, it is not broken for a long time, so it must be one of the recent changes

**Comment by airblade** [comment]
I can't reproduce this problem.  Is your vimrc online anywhere?

**Comment by petermehle** [comment]
No, I dont have it online. I disabled all plugins and I had only gitgutter installed and the problem persisted, so it looks like there is no conflict with other plugins. 
It looks like that mark is always set to the beginning of the file, so it always select the whole file.

**Comment by airblade** [comment]
I can reproduce this now but it's a bit of a weird bug.  I'll keep investigating.

**Comment by robinoburka** [comment]
Hi, I have the same problem. The trick to reproducing this issue is to try it on file that is tracked by Git.

Open some file tracked by Git, copy few lines, paste them anywhere. And now: You should be able to use `[v`] to reselect previously selected area. `[ Should point to the first selected line. With active gitgutter plugin the command `[ points to the first line of file.

I really like gitgutter, but `[v`] is killer-featrue.

**Comment by airblade** [comment]
The `` `[ `` and `` `] `` marks are set whenever an operator is used on the buffer.  The strange thing is that vim-gitgutter doesn't use any operators on the buffer: it doesn't touch a buffer's contents.

Therefore I tentatively think this may be a bug in Vim.  However something in vim-gitgutter is causing / triggering this problem and I haven't managed to track that down yet (lots of other things on my plate...).

**Comment by airblade** [comment]
Before 0cb1e41 (see #232) vim-gitgutter handled realtime diffs by passing the buffer's contents as the second argument to `system()`.  That commit changed the mechanism to write the buffer's contents to a temp file instead.

It turns out that this has side-effects including resetting the ``'[`` and ``']`` marks.  The solution is to save and restore those marks explicitly (e098491).

**Comment by petermehle** [comment]
It works now, great!
