### ISSUE TITLE
grey column in neovim

### ISSUE THREAD

**Issue by mclearc** [airblade/vim-gitgutter#243]
I'm having trouble getting gitgutter to display correctly in neovim. There is a constant grey background to the column as illustrated [here](https://www.dropbox.com/s/8i6m3ggk588u5ce/Screenshot%202015-03-28%2014.37.44.png?dl=0). The symbols display but always with the grey column, making them hard to see (plus I dislike the grey column anyway). 

If I use  `:highlight clear SignColumn`  parts of the grey highlight go away, but wherever there are git symbols the grey remains. This does not seem a problem localized to Solarized, as it appears in other color schemes I try. It is not a problem with the same vimrc settings in either macvim or terminal vim. I am at the most current version of neovim (0.0.0-alpha+201503281204).

**Comment by airblade** [comment]
Thanks for letting me know.  I'll take a look.

**Comment by airblade** [comment]
That grey background was set by your solarized colorscheme.  There's a long-standing issue at altercation/vim-colors-solarized#26 to make it easier on the eye.

The reason the grey background remained on existing signs when you cleared the sign column's highlight was that vim-gitgutter didn't know you had changed the highlight.  When a colorscheme is loaded the plugin figures out the sign column's background colour and uses that for the background colour of the signs.  If you subsequently change the background colour, vim-gitgutter doesn't know – unfortunately updating a highlight group doesn't trigger any kind of autocommand for us to listen to.

To have vim-gitgutter pick up any highlight changes, do this: `:call gitgutter#highlight#define_sign_column_highlight()`.

However that's all by the by because I've pushed 07d7c9d which overrides the sign column highlight by default.  You won't need `:highlight clear SignColumn` and it should fix things on neovim (or at least it does on my version: 0.0.0-alpha+201502182054).

**Comment by mclearc** [comment]
Thanks very much. This worked, and I appreciate the explanation. Great plugin!
