### ISSUE TITLE
Add a command to stage / revert a hunk?

### ISSUE THREAD

**Issue by phorust** [airblade/vim-gitgutter#244]
Something like `:GitGutterToggleHunk`, which stages the hunk if not staged and unstages the hunk if it was staged? I think this would be very useful and cover most use cases of staging hunks.

**Comment by airblade** [comment]
When a hunk is staged it doesn't show up as a diff any more so there's no way to unstage it with the current implementation.

vim-gitgutter supports staging and reverting hunks but not unstaging.  To support unstaging we'd have to diff the index against the repo instead of the working tree against the index – but that would complicate things more than I'd like.

**Comment by airblade** [comment]
Closing this now but feel free to post any further comments.
