### ISSUE TITLE
Error on file switching

### ISSUE THREAD

**Issue by damionjn** [airblade/vim-gitgutter#274]
Receive the following after working for a bit, having multiple buffers open then switching files with https://github.com/rking/ag.vim fuzzy finder:

```
Error detected white processing function gitgutter#process_buffer..gitgutter#diff#run_diff:
line 71:
E89: No write since last change for buffer 33
```

This causes a segmentation fault and crashes vim every time.

NVIM 0.0.0-alpha+201507262350
Using `nvim -p` command

After pressing enter to choose the file to edit:
![screen shot 2015-10-17 at 1 33 40 pm](https://cloud.githubusercontent.com/assets/7221494/10560979/de62ad5a-74d8-11e5-90c4-58c3b36f4ab8.png)

**Comment by airblade** [comment]
It looks like vim-gitgutter is trying to process some "fake" buffer used by ag.vim.  ag.vim writes its search results in a split window: perhaps that's the one vim-gitgutter is having trouble with.

I think a workaround for the symptom might be to use `silent!` instead of `silent` [here](https://github.com/airblade/vim-gitgutter/blob/a30ee7f23e93c827b4857d337f04c1ddf3c0c16e/autoload/gitgutter/diff.vim#L85).  It would be better to address the cause, i.e. to stop vim-gitgutter processing ag.vim's non-file buffer.

Having said all that, I don't understand why the problem only manifests after a while, not the first time you use ag.vim.

**Comment by damionjn** [comment]
I've been away doing some work on an iOS project, but had some time yesterday to take a look at this. It didn't crash a single time. I'm unsure if it's because I was doing small commits (only activating gitgutter on 3-4 files at a time), but I'll go ahead and say #275 has fixed the issue. Thanks!

**Comment by airblade** [comment]
Thanks for the feedback.

So what version of vim-gitgutter are you running?  Is it the latest but with the patch in #275 applied?  I'm wondering whether you've got 62cfae4...

**Comment by damionjn** [comment]
airblade... I have no idea why, but it seems to work fine now.

I just spent 20 minutes opening files specifically with ag.vim and adding new lines for vim-gitgutter to mark. I did *not* have the latest- so I installed and re-tested editing each file in my project and this version seems to work also.

**Comment by airblade** [comment]
Thanks for testing it out again.  I'll assume everything's fine now unless I hear from you to the contrary.
