### ISSUE TITLE
GitGutter removes airline style 

### ISSUE THREAD

**Issue by muts** [airblade/vim-gitgutter#287]
I use mainly vim-airline but when I add vim-gitgutter it doesn't show the theme from airline. It does only when opening a new file. As soon as you save, :wq and re-open the file vim-gitgutter ruins the airline style. 

I hope this can be fixed asap, 'cuz vim-gitgutter is a satisfying plugin. Cheers.

**Comment by muts** [comment]
By saying "it doesn't show the theme from airline" I mean that the status line and the buffer tabs are visible but have no style at all. Only when :AirlineRefresh is called or going into insert-mode.

This should be fixed to integrate with airline properly.

**Comment by airblade** [comment]
I'd be surprised if this were caused by vim-gitgutter because vim-gitgutter doesn't touch the statusline or vim-airline's styles.

vim-gitgutter provides the function [`GitGutterGetHunkSummary()`](https://github.com/airblade/vim-gitgutter/blob/1aed46c072fd9bd00650474e89f0e4d3a483dad8/plugin/gitgutter.vim#L119) which vim-airline [calls](https://github.com/bling/vim-airline/blob/14d14cf951c08fc88ca6c3e6f28fe47b99421e23/autoload/airline/extensions/hunks.vim#L52); it doesn't do anything beyond that from vim-airline's point of view.

I installed vim-airline and try to reproduce your problem but I wasn't able to.

**Comment by muts** [comment]
I fixed it by added AirlineRefresh on vim enter. A lil' hacky way around it. 

fix in vimrc: autocmd VimEnter * :AirlineRefresh

**Comment by DannyFeliz** [comment]
Thank you man @muts I had this problem today

**Comment by airblade** [comment]
Glad you found a workaround.  For a more elegant solution I'd suggest opening an issue on vim-airline...
