### ISSUE TITLE
GitGutter autoincrements buffer count

### ISSUE THREAD

**Issue by ewk** [airblade/vim-gitgutter#297]
I recently noticed some strange behavior using Vim. The buffer count
was incrementing on its own.

After opening a few files in less than a minute, my buffer list would
look like this:

1  h    "FOO"        line 136
10 #h   "BAR"        line 29
55 %a + "FOOBAR.txt" line 7

Just a minor annoyance, except that my muscle memory expects to see
buffer numbers increase sequentially.

I tried to find the source of this odd behavior by running Vim without 
my .vimrc, but had no luck.

I then tried removing my plugins one by one, and when I removed vim-gitgutter
the problem went away.

Running Vim in debug mode with vim-gitgutter installed provided a clue:

$ vim -V13vimlog.txt

The log has a LOT of calls to gitgutter#process_buffer. Below is a sample:

continuing in function gitgutter#process_buffer

calling function gitgutter#process_buffer[19]..gitgutter#sign#update_signs

The buffer number here happens to be 19, but in the complete log output the 
buffer number gets quite large. These are not buffers that I've opened.

git bisect led me to commit 0cb1e41b23da: 

    Use a temporary file for buffer for realtime diffs
    
    .....

    Fixes #232.

The culprit appears to be the introduction of a single line in
autoload/gitgutter/diff.vim

\+    execute('silent write '.buff_file)

At the current HEAD -> master 3a810a9afccc, the same line in
autoload/gitgutter/diff.vim looks like:

    line 45     execute 'keepalt silent write' buff_file

I've tried removing this single line, and it does solve the problem. My buffer
count behaves normally again. And Vim's debug log has quieted down.

I've tested it on two different machines running different versions of Vim,
and I'm not seeing any regressions working with mixed Unix/DOS EOL files.

I'm also not seeing any changes running the plugin's test suite before or after 
removing the line.

The only reason I am not submitting a PR with this report is because I 
am not certain that removing this line will not introduce a new bug somewhere
else.

I think this line is just writing the temporary buff_file to disk (check the 
contents of ls!), but is it necessary for buff_file to be written every time?

**Comment by airblade** [comment]
Thanks for the detailed report.

vim-gitgutter does indeed currently cause the buffer numbers to increase much faster than otherwise.  I agree that despite not causing any problems it's surprising and inelegant.

As you surmised, it's because every time the plugin does a realtime diff:

- it writes the buffer contents to a temporary file;
- the writing of the temporary file causes vim to increment the next available buffer number, even though the temporary file is never loaded into vim.

You tracked down the reason for doing this: to work correctly with repos with CRLF conversion enabled (i.e. `core.autocrlf` is `true` or `input`) (#232).  This isn't quite the same as files with mixed line endings, as far as I understand.

This came up on [stackexchange](http://vi.stackexchange.com/a/5846) and @chrisbra suggested reusing the temporary files to avoid vim incrementing the buffer number.  I plan to try that.

I'm puzzled the plugin continued to work when you commented out line 45.  When I comment it out the realtime diff stops working: all the signs disappear.  Does it really still work for you?

(I think the tests continued to pass because there isn't a test for the realtime diffs yet.)

**Comment by ewk** [comment]
Well I feel a little silly I didn't find that stackexchange thread when I started debugging this. 

I gave you the wrong line number in my initial report. Sorry about that. 

At the current HEAD -> master 3a810a9, I changed line 85 of autoload/gitgutter/diff.vim to comment out writing the temp buffer.

@@ -82,7 +82,7 @@ function! gitgutter#diff#run_diff(realtime, use_external_grep)
   if a:realtime
     call delete(blob_file)
     call delete(buff_file)
\-     execute 'keepalt silent! bwipeout' buff_file
\+    " execute 'keepalt silent! bwipeout' buff_file
   endif

After using it some more, I found that it does not completely solve the problem. (I think some of the test files I used last time were not in Git repos.) ls! now shows Vim is generating a single temp file instead of tens of temp files for each real buffer. It's a big improvement.

My original concern with this solution is still there: what are the possible side effects of deleting this line?

**Comment by airblade** [comment]
Line 85 is there to stop vim filling up with unlisted buffers (which you can see with `:ls!`).  It doesn't prevent vim incrementing the buffer number each time it runs a realtime diff.

The unlisted buffers slow down plugins which iterate over buffers such as, apparently, YouCompleteMe.  See #258.  Interestingly it seems not everybody gets the unlisted buffers but I certainly do.

**Comment by airblade** [comment]
I've pushed a change (a871d857) which fixes this for me.  Please could you try it and let me know if it works for you?

**Comment by ewk** [comment]
Well I knew I was missing some componenet of understanding this ...

I pulled in your changes this morning and tested with some more repos. And now I'm only seeing Vim create a single file in /tmp. 

Thanks for the fix.
