### ISSUE TITLE
gitgutter#revert and git revert

### ISSUE THREAD

**Issue by olshevskiy87** [airblade/vim-gitgutter#306]
hi!
thank you for this useful plugin!)
maybe GitGutter Revert should be renamed to something like Rollback? As far as I can see there nothing common with `git revert` command, isn't it?

**Comment by airblade** [comment]
That's a good point.  In the context of this plugin, revert means to throw away the changes in an unstaged hunk and go back to what was there before.  It's nothing to do with `git revert`.

Here are some other words we could use instead:

- rollback
- undo
- discard
- drop

Can you think of any others?

I quite like `undo` because the action we're performing is similar to undoing "normal" changes in vim.

**Comment by olshevskiy87** [comment]
as for me - `undo` looks good. it's better than `rollback` )
