### ISSUE TITLE
gitgutter error on start?

### ISSUE THREAD

**Issue by hholst80** [airblade/vim-gitgutter#348]
I get this error message at start.
```
"test.f" 3L, 48C
Error detected while processing function gitgutter#utility#git_supports_command_line_config_override..gitgutter#utility#git_version:
line    1:
E484: Can't open file /tmp/vHWV005/0
Press ENTER or type command to continue
```

```
$ git --version
git version 2.1.4
```

**Comment by airblade** [comment]
What OS are you on?  I remember you were using Windows last time (#308) but that path looks unixy.

Does `:echo system("git --version")` work?

**Comment by auggo** [comment]
I can follow up on this — essentially, gutter tries to check non-repository files, and returns the error. I'm pretty sure you've worked on this before, but it seems to have turned up again.

![Here's the error](http://i.imgur.com/UbnuuEF.png)

:echo system("git --version") returns "git version 2.9.0.windows.1"
Vim :version is 7.4 32 bit Windows GUI.

**Comment by airblade** [comment]
Thanks for the additional information.

When vim-gitgutter loads the first thing it does is establish which version of git is in use.  It does this by [calling `system('git --version')`](https://github.com/airblade/vim-gitgutter/blob/09b9144002e938844df74f48ac72c1e3118e7d39/autoload/gitgutter/utility.vim#L177).

The strange thing is that the same call worked when you ran it by hand.

Furthermore I don't see why this call would only fail for non-repository files.

**Comment by auggo** [comment]
Found it — had launched gvim from two different shells — my system cmd, which doesn't inherit git, and git's CMD shell, which preloads it up. Running `:echo system('git --version')` on a vim whose shell doesn't support git returns the temp error.

Ultimately, no need to change anything, just specify in the readme that users who don't have git preloaded must specify their git executable, otherwise they will get:

![Error](http://i.imgur.com/DAqkSMw.png)

**Comment by airblade** [comment]
Glad you solved it.

So is there a scenario where you don't get the "cannot find git" warning but you do get the E484 tempfile errors?

**Comment by auggo** [comment]
As a matter of fact yes — with Git's Bash shell for Windows, even though git is preloaded on the shell.

This is because vim can't recognize the Bash shell, and instead defaults to default cmd when running `:return system('git --version')`, which then returns the temp error as expected. Not sure how you'd make a workaround for this, though.

**Comment by airblade** [comment]
Thanks for the extra information, and well done figuring it all out.

**Comment by airblade** [comment]
@hholst80 Does adding git to your shell's path resolve the problem for you?

**Comment by songxin1990** [comment]
You just need configure your Git environment variable.Add GIT_HOME='C:\Program Files\Git',then  modify PATH,add ;%GIT_HOME%\bin;
That's all.
