### ISSUE TITLE
GitGutter signs/lines not showing up in Vim build 7.4.2180

### ISSUE THREAD

**Issue by simonced** [airblade/vim-gitgutter#367]
I don't know at what build number it broke, but in `1832` it's working.

It might not be a problem with the plugin itself, though I thought I could report in nonetheless.

It was the Win 64bit version. Never had problems with those builds before, they come from https://tuxproject.de/projects/vim/

**Comment by dertuxmalwieder** [comment]
Just in case: These builds are mine, they are not modified from the original Vim. :)

**Comment by airblade** [comment]
It's working for me on Vim 7.4.2028.  I'll upgrade to 2180 and see what happens.

**Comment by simonced** [comment]
@dertuxmalwieder your builds are great, I use them since I started using Vim.

**Comment by airblade** [comment]
Do they signs show up if you do `let g:gitgutter_async=0`?

**Comment by dertuxmalwieder** [comment]
@simonced Thanks. ;-)

**Comment by simonced** [comment]
@airblade 
Sorry for the late answer.  
Yes the sign appeared right away! I'll let that setting in my config then.  
Thank you very much, I would have never found that!

**Comment by airblade** [comment]
@simonced Do you have this problem on Vim 8 without `let g:gitgutter_async=0`?

**Comment by simonced** [comment]
@airblade I started using Vim 8.0.003 yesterday. The flag `g:gitgutter_async=0` is still needed.
If I let it be `1` as default, signs are not appearing anymore.

**Comment by airblade** [comment]
Thanks for the info.  Please could you paste the result of `:GitGutterDebug`?

**Comment by airblade** [comment]
I've just thought of a possible cause.  If you launch Vim without editing any files, what does `:echo &shell &shellcmdflag &shellredir` produce?

**Comment by simonced** [comment]
@airblade  sorry for my late answer, here are the results of the 2 commands:

    :GitGutterDebug

=>

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 15 2016 20:05:13)
    MS-Windows 64-bit GUI version with OLE support
    Included patches: 1-5
    
    git version 1.9.5.msysgit.0
    
    'grep' n'est pas reconnu en tant que commande interne

=

    :echo &shell &shellcmdflag &shellredir

=>

    C:\WINDOWS\system32\cmd.exe /c >%s 2>&1

**Comment by airblade** [comment]
Thanks for that.

The problem presumably lies in the async code because the synchronous code works fine.  The most likely culprit is how the async jobs are invoked.  On Windows they're invoked like this ([here](https://github.com/airblade/vim-gitgutter/blob/402257f920ea7e75af6c0a0c1a33ec4c0cd9d4a8/autoload/gitgutter/async.vim#L29) and [here](https://github.com/airblade/vim-gitgutter/blob/402257f920ea7e75af6c0a0c1a33ec4c0cd9d4a8/autoload/gitgutter/async.vim#L64)):

```viml
let command = ["cmd.exe", "/c", a:cmd]
```

I'm assuming `cmd.exe` is on your path but, just to be sure, please could you try changing those lines to use `C:\WINDOWS\system32\cmd.exe` instead of `cmd.exe`?

Also please can you try `let g:gitgutter_log=1` (without `let g:gitgutter_async=0`), save a buffer to trigger the plugin, then post the `gitgutter.log` and `channel.log` files in the directory where the plugin is installed?

**Comment by simonced** [comment]
Hi there, I did the tests, surprisingly the signs appeared.

I modified the line you indicated:

    let command = ["C:\WINDOWS\system32\cmd.exe", "/c", a:cmd]

and I used the following 2 commands before testing editing a file:

    let g:gitgutter_log=1
    let g:gitgutter_async=1

and here are the results of the logs (a bit long):
[channel.log](https://gist.github.com/simonced/dd9fb2b59f96993be932339f483aa321)
[gitgutter.log](https://gist.github.com/simonced/18e832f9646d396014d05f9343b5411c)

**Comment by airblade** [comment]
So, to confirm, the plugin without any modification works asynchronously for you now?

**Comment by airblade** [comment]
It won't be anything to do with Ruby or Python since the plugin is pure vimscript.

I suspect git is installed differently on your computers, perhaps via msys / msys2 / msysbash / msysgit / etc.  I don't know what any of that is, as I haven't used Windows for a long time, but it seems to affect the path available to vim.  See #150 for an example.

**Comment by simonced** [comment]
The git command is in the path since I use it through different interfaces (bash, vim, git extensions etc).

The async flag is still needed on one of the computers despite the versions of vim and windows being the same.

What I wanted to say is that on my home computer, the async flag is on and the signs appear, but not at work...

**Comment by airblade** [comment]
To be honest running the diffs asynchronously doesn't make much difference; the slowest part of process is inside vim, updating the signs.

But if you'd like to keep debugging this, please could you run the plugin asynchronously on your work computer and post the logs as you did above?

**Comment by simonced** [comment]
You'r right, since I narrowed down that particular problem to one machine only (and it works with the async flag turned off), there is nothing to be done on the plugin side.

Thank you for your help, I've learned a lot in the process ;)

**Comment by airblade** [comment]
Glad we got there in the end!
