### ISSUE TITLE
-U0 prevents --compaction-heuristic

### ISSUE THREAD

**Issue by rhysd** [airblade/vim-gitgutter#371]
I like `--compaction-heuristic` which was added in Git 2.9.  So I added it to `g:gitgutter_diff_args`.

```vim
let g:gitgutter_diff_args = '--compaction-heuristic'
```

But it did not work.  I investigated the problem and adding `-U0` option `git diff` prevented it. I did `git blame` and cc77f32 had added the option.  But I didn't know why it was added from the commit. Could you tell me the reason?

**Comment by airblade** [comment]
The plugin has always used `-U0`; here's the [very first version](https://github.com/airblade/vim-gitgutter/blob/843ee5aed667283e635a7530f97ebb17795da942/plugin/gitgutter.vim#L51).

The surrounding context is ignored because it complicates the marking up of lines which have changed.  Having the context changes the line numbers and line counts of each hunk and the context is irrelevant when it comes to placing signs.

Doubtless one could add extra code to take account of and then ignore the context, but right now it seems like more complexity than it's worth.

**Comment by rhysd** [comment]
Oh, I understood. So `--compaction-heuristic` is not available for vim-gitgutter :sob: Thank you for the answer.

**Comment by blueyed** [comment]
@rhysd 
Just out of curiosity (since I just filed https://github.com/airblade/vim-gitgutter/issues/425): what is the benefit of `--compaction-heuristic', which seems to add extra whitespace to the diff, which would not get reflected in the gutter then anyway?!

**Comment by rhysd** [comment]
@blueyed Please read an explanation in this release note. https://github.com/blog/2188-git-2-9-has-been-released

**Comment by blueyed** [comment]
Ah, I misunderstood it then.
It has been removed in Git v2.11.0-rc0-8-g3cde4e02e however, and `--indent-heuristic` has been added, which has the same problem.
I've came up with a patch for Git: https://public-inbox.org/git/20170623103612.4694-1-git@thequod.de/T/#u.
Let's continue any discussion in https://github.com/tomtom/quickfixsigns_vim/issues/74#issue-237900460.
