### ISSUE TITLE
GitGutterDisable not working immediately after tab split

### ISSUE THREAD

**Issue by rshkv** [airblade/vim-gitgutter#375]
Hi,

I'm using [Goyo](https://github.com/junegunn). It attempts to hide GitGutter, but the signs remain (with nvim 0.1.4 and Vim 8):

<img src="https://www.dropbox.com/s/bd5eomveisau61e/gitgutter.png?dl=1" width="300px" />

Its [author pointed out to me](https://github.com/junegunn/goyo.vim/issues/128) that this might be due to GitGutter's behavior on tab splits. This snippet:
```vim
" GitGutterDisable immediately following tab split does not clear signs
tab split | GitGutterDisable
```
will fail to disable GitGutter (however, it works the second time it's called). Again, both Vim versions.

**Comment by airblade** [comment]
The problem was the diffs were running asynchronously and the callbacks weren't checking whether GitGutter was active before updating the signs.  So `tab split | GitGutterDisable` did this:

1. `tab split` -> triggers `TabEnter` autocommand -> runs diff asynchronously.
2. `GitGutterDisable` disables GitGutter.
3. The job from (1) calls back and (without checking whether GitGutter is active) updates the signs.

**Comment by rshkv** [comment]
I understand! 

Thank you very much, @airblade.
