### ISSUE TITLE
Can't enable and go to the next hunk in one statement?

### ISSUE THREAD

**Issue by Ran4** [airblade/vim-gitgutter#391]
`nnoremap <leader>gn :GitGutterEnable<cr>:GitGutterNextHunk<cr>`

After running the mapping, GitGutter is enabled, but it won't go the next hunk unless it was already enabled before running the mapping.

Why is this happening? How would you do both in one go?

**Comment by airblade** [comment]
Enabling gitgutter means it can process the buffer, not that it should process the buffer now.  You should insert a `:GitGutter` or `:GitGutterAll` after the enable command.

**Comment by Ran4** [comment]
`nnoremap <leader>gn :GitGutterEnable<cr>:GitGutter<cr>:GitGutterNextHunk<cr>` exhibit the same behaviour? That is, it needs to be entered twice in order to activate gitgutter and go to the next hunk.

**Comment by airblade** [comment]
It works for me with a single invocation.  Here's what I did:

1. Start vim and edit a file.
2. `:nnoremap <leader>gn :GitGutterEnable<cr>:GitGutter<cr>:GitGutterNextHunk<cr>`
3. `:GitGutterDisable`
4. Make a change somewhere in the file and move the cursor to the top.
5. `\gn`  (my leader key is `\`).

What happens if you start vim with a bare-bones vimrc, and all other plugins disabled/removed?
