### ISSUE TITLE
Opening a file through fugitive.vim's status does not update hunk locations

### ISSUE THREAD

**Issue by dmcinnes** [airblade/vim-gitgutter#406]
The markers are updated but whenever I do `]c` to get to the next hunk, it appears to use the previous file's hunks.

**Comment by dmcinnes** [comment]
Should also note, if I select the file again from the fugitive status window it starts working.

**Comment by airblade** [comment]
I've been noticing the same thing on and off over the past few weeks, though without fugitive.

I'll investigate properly when I get back from holiday...

**Comment by airblade** [comment]
Currently gitgutter stores a single set of hunks, which are assumed to be the current buffer's, instead of each buffer storing its own hunks.

The hunk-jumping code assumes that the hunks have already been calculated for the buffer.  So if gitgutter hasn't run a diff for the current buffer, the hunks will still be the previous buffer's.

GitGutter runs on TabEnter/BufEnter.  With "real time" processing, which is the default, it won't run a diff if there haven't been any changes to the buffer.  This would result in stale hunks.

In contrast signs are stored per buffer.

I can't see any way for signs but not hunks to be updated.  Perhaps you mean the signs are correct for the buffer, i.e. "updated" from the previous buffer's?

I think the best solution is for gitgutter to store hunks per buffer.  I'll post an update when it's ready.

**Comment by airblade** [comment]
I have the hunks buffer-local in 8576f00.  Please could you try it out and let me know if it fixes your problem?

**Comment by dmcinnes** [comment]
@airblade it works! Awesome, thank you! 🎉 

And thank you for such an awesome plugin!

**Comment by airblade** [comment]
:)
