### ISSUE TITLE
conflict with ctrlp-funky

### ISSUE THREAD

**Issue by tracyone** [airblade/vim-gitgutter#408]
[tacahiroy/ctrlp-funky](https://github.com/tacahiroy/ctrlp-funky)

see [ctrlp-funky/issues/85](https://github.com/tacahiroy/ctrlp-funky/issues/85)

**Comment by airblade** [comment]
Are you using the latest version of gitgutter?

**Comment by tracyone** [comment]
yes, sure.

**Comment by airblade** [comment]
What is the `&buftype` of the buffer ctrlp-funky briefly switches to?

**Comment by tracyone** [comment]
**nofile**

**Comment by airblade** [comment]
OK, so presumably the interference comes when ctrlp-funky switches back to the original buffer (gitgutter will ignore the `nofile` buffer).

gitgutter should keep track of which buffer it is processing, so even if the buffer is changed by something else while it is processing asynchronously, it'll still update the correct buffer's signs.

I'm not familiar with ctrlp nor ctrlp-funky so I don't really know what the problem is.

**Comment by tracyone** [comment]
Following is the solution....

```vim
"handle bug of gitgutter
function! s:ctrlp_funky()
    let g:gitgutter_async=0
    :CtrlPFunky
    let g:gitgutter_async=1
endfunction
nnoremap <c-k> :call <SID>ctrlp_funky()<cr>
```
