### ISSUE TITLE
Grep used very unportably

### ISSUE THREAD

**Issue by Rycieos** [airblade/vim-gitgutter#410]
While the ability to overwrite the default grep command is given, it is hard to do so on a environment by environment basis. Having the plugin automatically detect options and adjust would be better.

The first issue is that the `-e` flag is turned on. This seems to be a case of superfluous extended grep, as the string being grepped for (`^@@ `) does not use any extended features. This causes problems for any environments without extended grep support. I have tested the removal of `-e` with both GNU grep and grep without `-e` support, and it works the same as before.

The second problem is the default `--color=never`. This is a problem for greps without color support, as they will crash on reading this flag. Solving this one is interesting, as it could be argued that this flag would never be needed as the default of grep is not to have color, and vim shouldn't be reading aliases. Even if it does, hopefully the alias would be `grep --color=auto`, which would hopefully not be showing color here.

Otherwise, having color supported could be tested by doing something like this:
```
:call system("echo 'test' | grep -q --color=never 'test'")
if v:shell_error
  let s:grep_command = 'grep'
else
  let s:grep_command = 'grep --color=never'
endif
```

**Comment by airblade** [comment]
Grep has been discussed in several previous issues.

One complaint was that testing whether grep supports the colour flag slows down vim's startup time too much.

**Comment by Rycieos** [comment]
I did search for related issues, but must have missed those discussions.

I don't think it would add that much startup time, but I could always add that bit of code to my vimrc instead.

Is the `-e` extended discussion worth having?

**Comment by airblade** [comment]
I think you're right about not needing extended grep.  When I added grep to gitgutter in 79fa8ca I included the `-e` flag.  Whether that was force of habit from my own use or whether I thought it was necessary for the `^` anchor, I can't remember.  It has stayed there ever since.  I'll remove it.

Regarding `--color=never`, I've gone full circle on this.

Initially it wasn't there.  Then I added it because some people had grep always producing colourful output (e.g. #231).  Then I put it behind a guard (#235) because some greps don't support it (#234).  Then I removed the guard because it made vim's startup too slow (#296).

Now I'm just going to take it out because, as you pointed out, it shouldn't really be necessary.

**Comment by Rycieos** [comment]
It shouldn't be necessary, but as you pointed out, at least one person had an issue with it. I still think it shouldn't be a default option, so just in case anyone has this problem in the future, here is how it could be fixed.

If grep is running in color mode on at least one of your systems, you can add this to your .vimrc:
```
call system("echo 'test' | grep -q --color=never 'test'")
if !v:shell_error
  let g:gitgutter_grep_command = 'grep --color=never'
endif
```

**Comment by airblade** [comment]
That's a useful snippet.  Thanks.

**Comment by brodock** [comment]
I'm seeing this behavior again with recent `vim-gitgutter` in neovim. I tried to enable logging but couldn't find a log file in `~/.local/share/nvim/` (using Mac OS)

And my situation is similar, I have `$GREP_OPTIONS` defined as `--color=auto`
