### ISSUE TITLE
GitGutter not working on maxOS Sierra

### ISSUE THREAD

**Issue by alexanderVonBergner** [airblade/vim-gitgutter#426]
Hello,
thank you for the gread vim plugin. I love using it on linux.
I currently try to set up vim on macOS Sierra. I installed vim from homebrew and i am using it together with the plugins:
```
Plugin 'gmarik/Vundle.vim' 
Plugin 'tpope/vim-fugitive' 
Plugin 'scrooloose/nerdtree'
Plugin 'hdima/python-syntax'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/syntastic'
Plugin 'davidhalter/jedi-vim'
Plugin 'jiangmiao/auto-pairs'
```
Unfortunately I cannot get gitgutter working properly. When I edit a .tex file, gitgutter does not start automatically. I can make it work by doing `:GitGutterEnable` inside vim, but with every change to the file, I have to `:GitGutterEnable` again. If I edit .py-files, I cannot get gitgutter to do something at all.
My .vimrc settings for gitgutter:
```
let g:gitgutter_enabled = 1                                                                                                       
let g:gitgutter_signs = 1
let g:gitgutter_updatetime = 750
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
```

Do you have a suggestion what I could do?
Please let me know, if you need further information.

Thanks,
Alex

**Comment by airblade** [comment]
Do you have Syntastic showing signs in the sign column?  If so, that would conflict with gitgutter because there is only one sign column and no way for plugins to share it nicely.  You could test this by uninstalling Syntastic or configuring it not to show signs.

Also, you don't need the `let g:gitgutter_enabled=1` or `let g:gitgutter_signs=1` as those are the default values.

The `let g:gitgutter_updatetime=750` is wrong.  Replace that with `set updatetime=750` – it's a vim option not a plugin one.

**Comment by alexanderVonBergner** [comment]
Thank you very much for the quick support. That was the problem. Disabeling Syntastic did the job.
