### ISSUE TITLE
Display on all open windows on vim open

### ISSUE THREAD

**Issue by AnthonyAstige** [airblade/vim-gitgutter#428]
Using `vim -o *.js` to open multiple files at once gitgutter only displays on the first window.

Would be nice if this were in the core plugin somehow, but for now I've added this to my `.vimrc` to display gitgutter in all windows on open.

`autocmd VimEnter * if winnr() != winnr('$') | :GitGutterAll | endif`

**Comment by airblade** [comment]
I had assumed that `TabEnter` would be fired when loading Vim with some files, which would [display the signs for all windows](https://github.com/airblade/vim-gitgutter/blob/dcac1f74ee5c26125363dca164463bde6657c838/plugin/gitgutter.vim#L201-L209), but evidently it isn't.

I added some `echom` statements and ran `vim -o Gemfile Rakefile`:

```
"Gemfile" 44L, 1126C
BufEnter: bufnr 1
"Rakefile" 21L, 543C
BufEnter: bufnr 1
VimEnter
```

Annoying when the `BufEnter` is fired for the second file (`Rakefile`) the effective buffer number is still `1` so gitgutter just processes the first file again.

Your solution would work at the cost of re-processing the first buffer unnecessarily.  But since that happens anyway for each file opened, it wouldn't make things much worse.
