### ISSUE TITLE
PreviewAllHunks

### ISSUE THREAD

**Issue by goschevski** [airblade/vim-gitgutter#436]
Hi,

I really like preview hunk option, it's much more cleaner than fugitive diff for me.
It would be awesome to be able to preview all hunks (they could be divided with bunch of minuses (----------) for example.
Unfortunately I don't know vim-script so I can't create pull request.

Is there any changes that you can add this feature?

**Comment by airblade** [comment]
When you have more than one hunk, I think you would want some kind of contextual information to tell which line numbers the hunk is in, and which file (if you want to see hunks across multiple files).

It reminds me a little of having the ability to fold up everything except the hunks (#286).

I can see the benefit, I think, but realistically I'm not going to be implementing this due to a lack of time.

**Comment by goschevski** [comment]
I would use it just for the current file (not multiple files). 

Thanks anyway. ;)
