### ISSUE TITLE
E139: File is loaded in another buffer

### ISSUE THREAD

**Issue by thallada** [airblade/vim-gitgutter#454]
This error has been driving me insane for months and I had to disable gitgutter because of it. Whenever I edit a file and wait a few seconds without saving, this error interrupts me:

```
Error detected while processing function gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line   35:
E139: File is loaded in another buffer
Press ENTER or type command to continue
```

It also whenever I switch tabs or when vim regains focus from another window.

When searching for this issue, I found this: https://github.com/rogual/neovim-dot-app/issues/229

But I am not using neovim, I am using Vim 8.0.

Any idea how I could fix this? I really like this plugin and I hate to have to disable it.

**Comment by airblade** [comment]
How odd.  It's the first I've heard of this.

Which exact version of Vim are you using?  And is your vim-gitgutter up to date?  Is your vimrc, and list of other plugins, online somewhere?

**Comment by thallada** [comment]
Ah, I was hoping others might be experiencing it. I will try uninstalling some plugins to see if it's an interaction with another plugin that's causing it.

**Comment by zackhsi** [comment]
I have also been experiencing this for some months, though I have not taken the time to debug—😬.

Love the plugin, thanks!

**Comment by thallada** [comment]
I narrowed down the issue to an interaction between this plugin and [ale](https://github.com/w0rp/ale). However, now I'm getting a different error. Not sure why.

If I open up two side-by-side splits and then edit a python file in one without saving, move to the other split, and then move focus back I get this error:

```
Error detected while processing function gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line   35:
E768: Swap file exists: /home/tyler/.vim/swap/9.py.swp (:silent! overrides)
Press ENTER or type command to continue
```

**Comment by niklascarlsson** [comment]
I just started using VimWiki yesterday and this error message keep appearing now for me as well when I have an unsaved file open for too long.

I am running neovim + gitgutter and wimwiki plugin

```
Error detected while processing function gitgutter#process_buffer[10]..gitgutter#diff#run_diff:
line 35:
E139: File is loaded in another buffer
```

**Comment by airblade** [comment]
I still can't reproduce this.  Can anyone give me specific steps to reproduce?

**Comment by Busimus** [comment]
I'm experiencing this bug, but with some other additional side effects (possibly whole other bug?).
[Here's a quick video](https://youtu.be/tkACRxPR0OM) of how I reproduce everything at once.

Written down, the process is as follows:
1. Open a file that's tracked by git, and open another split with a different buffer (I open just an empty one with `enew`, but the same thing happens with non-empty buffers as well).
2. Modify the contents of the empty buffer, doesn't matter if you write it to disk.
3. Modify the contents of the buffer with the file but don't write it to disk, keep the file in modified state.
4. Select the split with the not-empty-anymore buffer.
5. Force gitgutter to update (I do this by moving the mouse cursor to another screen and then back to the one with vim)

Several things happen at that point:
1. The gutter of the git-tracked file now appears to show the difference between it and the other buffer.
2. (if you didn't write the empty buffer to disk) The empty nameless buffer now gets a name `2.vim` and gets written to the `/tmp/nvim<random symbols>/2.vim`.
3. If you select the split of the git-tracked file, then you get the E139 error that this issue is about.

All this is very weird.
I run neovim 0.2.2 and was able to reproduce everything with a clean config. In regular vim step 5 gets replaced with running `GitGutterEnable` command.

**Comment by airblade** [comment]
@Busimus Thank you!  With your instructions I can finally reproduce this.
