### ISSUE TITLE
Improve pumvisible workaround in is_active?

### ISSUE THREAD

**Issue by blueyed** [airblade/vim-gitgutter#481]
I've wondered about `pumvisible()` being used in `gitgutter#utility#is_active` (https://github.com/airblade/vim-gitgutter/blob/1a6be0223e65f60e7fd54e790543108a813f573f/autoload/gitgutter/utility.vim#L47), and found that it is meant as a workaround for when a preview window might be there.

It was added in https://github.com/airblade/vim-gitgutter/commit/f05fda98b28adc6f3047ed25027c13e265ed7bc0 to fix #310.

I think a better fix would be to check for the local `previewwindow` setting or something similar.

I have not investigated yet, but just started using vim-gitgutter and wanted to leave this here for now.

**Comment by airblade** [comment]
> I think a better fix would be to check for the local previewwindow setting or something similar.

So similar to the way we check whether [the buffer holds an ordinary file](https://github.com/airblade/vim-gitgutter/blob/1a6be0223e65f60e7fd54e790543108a813f573f/autoload/gitgutter/utility.vim#L48) we could check whether the window is the preview window?

The trouble with window variables is that we only know the buffer number, not the window number.  This is why the slightly awkward [s:vimdiff()](https://github.com/airblade/vim-gitgutter/blob/1a6be0223e65f60e7fd54e790543108a813f573f/autoload/gitgutter/utility.vim#L195-L213) function exists.

Looking forward to hearing more on this...

**Comment by airblade** [comment]
I'm happy to leave the check for `pumvisible()` in place because I don't think we want gitgutter to run while the user is in the middle of a completion.

Gitgutter could additionally check whether the buffer it is processing is shown in a preview window – but if the preview window is showing a git-tracked file then we would probably want to see the diff signs if any.

I'll close this for now but happy to discuss further if you like.
