### ISSUE TITLE
Not updating on BufEnter

### ISSUE THREAD

**Issue by relapi** [airblade/vim-gitgutter#490]
> What is the latest commit SHA in your installed vim-gitgutter?
b27ee4d602d7ce6f7b7caf8e9ecb8eded57ffe0a

> What vim/nvim version are you on?
8.0.1500

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

Buffers are only updating when I edit them, not on BufEnter.

**Comment by airblade** [comment]
Presumably `:au gitgutter BufEnter` prints out an autocommand?

**Comment by relapi** [comment]
Yep, it prints out: `*         if gettabvar(tabpagenr(), 'gitgutter_didtabenter') |   call settabvar(tabpagenr(), 'gitgutter_didtabenter', 0) |   call gitgutter#all(0) | else |   call gitgutter#init_buffer(bufnr('')) |   call gitgutter#process_buffer(bufnr(''), 0) | endif`

**Comment by airblade** [comment]
In that case it should update on `BufEnter`.

What makes you think it isn't?

**Comment by relapi** [comment]
Hmm, it doesn't update for me though. And adding my own autocommand that runs :GitGutterAll on bufenter makes things work correctly. Below are repro steps.

```
mkdir test
cd test
echo "a\nb\nc\n" > a.txt
echo "d\ne\nf\n" > b.txt
git init
git add --all
git commit -m "blah"

echo "ab\nb\ncd\n" > a.txt

vim a.txt
:split b.txt

# in terminal
git add --all
git commit -m "blah"

# back in vim
# switching between buffers doesn't cause the signs in a.txt to disapper
```

**Comment by relapi** [comment]
Really it seems like real time update aren't working at all for me anymore (only time updates happen is on save)

**Comment by relapi** [comment]
Adding in my own autocmd: `autocmd BufReadPost,CursorHold,CursorHoldI,WinEnter * :GitGutterAll` seems to fix things for me, so seems like there might be something wrong with how the plugin is running autocmds.

**Comment by relapi** [comment]
Another note: I checked out 932ffaca092cca246b82c33e23d2d3a05e192e08 and everything works as expected (without any config changes, of which I only have the sign column always enabled and updatetime set to 200)

**Comment by airblade** [comment]
Thanks for the repro steps – much appreciated.

The signs aren't updating when you switch back to vim because the [`FocusGained` autocmd](https://github.com/airblade/vim-gitgutter/blob/e512d3a6fc80900c24ef293b475715f49ec6ded8/plugin/gitgutter.vim#L232) isn't firing; only the [`BufEnter` autocmd](https://github.com/airblade/vim-gitgutter/blob/e512d3a6fc80900c24ef293b475715f49ec6ded8/plugin/gitgutter.vim#L220) fires.

The difference is the `FocusGained` one forces an update, whereas the `BufEnter` one only updates if the buffer has changed (to avoid unnecessary updates when entering a buffer).  The `GitGutter` and `GitGutterAll` commands also force an update.

The autocommands are set up on the assumption that your terminal is reporting focus events correctly to vim.  Evidently your terminal isn't, which is why the signs aren't updating when you expect.

**Comment by airblade** [comment]
I can reproduce this with my own terminal vim.  When I switch focus away and then back again, not only is `FocusGained` not fired – no events are fired.  Is that the case for you too?

**Comment by relapi** [comment]
Gotcha, re: `FocusGained`, but switching between buffers doesn't even update the file I switch to. e.g at the end of the repro running `:e a.txt` or `:e b.txt` (or switching the between splits) doesn't cause those buffers signs to be updated.

**Comment by airblade** [comment]
That's because `BufEnter` runs the non-force update which checks whether the buffer contents has changed since the last time, and only does a diff if it has.

In this case, neither `a.txt` nor `b.txt` has changed so `BufEnter` won't run a fresh diff.

Compare this with `:GitGutter` or `:GitGutterAll` which does a force-update.

**Comment by airblade** [comment]
I use [terminus](https://github.com/wincent/terminus) to get `FocusGained` working with my terminal vim.

**Comment by relapi** [comment]
Ahhhhh, closing this then. Thanks for the terminus suggestion I'll check that out.

**Comment by airblade** [comment]
Documented the reliance on `FocusGained` in 4a66a09.

**Comment by airblade** [comment]
If Terminus doesn't work out for you, you can now do this instead:

```viml
let g:gitgutter_terminal_reports_focus = 0
```

**Comment by P4Cu** [comment]
I've had the same problem but when I've opened a buffer from `` :Gst `` window. With either `` autocmd `` or `` let g:gitgutter_terminal_reports_focus = 0 `` it works again. Poor alacritty terminal :-(
