### ISSUE TITLE
Gutter for inactive tab does not get updated 

### ISSUE THREAD

**Issue by dylan-chong** [airblade/vim-gitgutter#525]
> What is the latest commit SHA in your installed vim-gitgutter?

commit a7206c41fc174f576b3f7085d48319dbdad760a5

> What vim/nvim version are you on?

NVIM v0.2.2

Steps To Replicate:

1. Make some changes to the current file in vim and save. There should be + signs in the gutter
2. Open a new vim tab so that the edited file is backgrounded
3. Open a new terminal and type `git add --all `
4. Go back to vim and go to the previous table where you made changes to the file. The plus signs are still in the gutter when they should not be

**Comment by airblade** [comment]
I can't reproduce this: in step 4 the signs are gone, as expected.  I'm using NVIM 0.2.2 on macOS with iTerm2.

I suspect the problem is that your terminal doesn't report focus events.  The plugin relies on `FocusGained` to update when you switch back to it after using another terminal.  If this diagnosis is correct, you can either use something like [Terminus](https://github.com/wincent/terminus) or set `let g:gitgutter_terminal_reports_focus=0`.

**Comment by airblade** [comment]
That's helpful to know.

I can reproduce this now – the inactive tab needs to be showing a file not in the active tab.

The problem is this: when you focus back on nvim, gitgutter picks up the focus event and force-updates the current tab.  When you change to another tab, it force-updates if focus events aren't supported or non-force-updates if they are (to avoid unnecessary work).  In your case, focus events are supported so when you change to the inactive tab, gitgutter sees that no modifications have been made to the buffer since last time and it doesn't update the signs.

**Comment by dylan-chong** [comment]
Interesting. Is it really that much work that is saved by not force updating? 

I'm curious. Are you able to reproduce this with or without tmux?

**Comment by airblade** [comment]
It doesn't save much work, but I try to make gitgutter as efficient as possible by avoiding any unnecessary processing.

I reproduced this without tmux; just nvim inside iTerm2.

I know how I'm going to fix it: setting a flag on each tab.  In the meantime, setting `let gitgutter_terminal_reports_focus=0` in your vimrc should fix it for you.

**Comment by dylan-chong** [comment]
Thanks. Just a thought, maybe this is a little tacky but what if you have a sort of time out - if gitgutter has already been triggered in the last 200ms, then don't bother trying again?

**Comment by airblade** [comment]
It effectively does that already by only running if the buffer has been modified since the last run.

**Comment by airblade** [comment]
Please can you update and see if the problem has been fixed?

**Comment by dylan-chong** [comment]
It works!
