### ISSUE TITLE
Feature request : GitGutterPreviewHunkToggle

### ISSUE THREAD

**Issue by windware** [airblade/vim-gitgutter#547]
> What is the latest commit SHA in your installed vim-gitgutter?

b4e43ae

> What vim/nvim version are you on?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 26 2018 12:36:50)
macOS version
Included patches: 1-202

I feel it would be convenient to have a toggle function for the preview as I want to quickly look at it and close and move on but to close it, currently I have to move to the preview window, close it to continue. (And as I use NERDtree, the focus goes back to the NERDtree window when closing the preview, there's an extra step to get back to the file buffer.)

**Comment by airblade** [comment]
You can close the preview window from anywhere with `:pclose` or `:pc`.  You could use this in a map.

There was something similar in #369 and #396.

**Comment by airblade** [comment]
Closing this but let me know if you have any further questions.

**Comment by bluz71** [comment]
Sorry to bump an old closed request, but does anyone have a good normal mode mapping that achieves this? I simply want a mapping that opens the preview window on the current hunk if it not opened, or closes if it is opened (much like NERDTreeToggle).

I have been trying all morning, but I can figure out a way to toggle the GitGutter preview hunk window. I am finding it hard to detect if the preview window is opened, and no `:pumvisible` does not help since it always returns `0` whether preview or opened or closed.

The hint provided in #369 appears to be using an old GitGutter API.

Help? I am sure a VimScript guru can cook up a recipe, alas I am no guru.

P.S. Yes, `:pclose` works, but it is not as elegant as toggling since my brain is used to toggles (NERDTree, UndoTree etc).

**Comment by bluz71** [comment]
Solved thanks to the help of @romainl at the Vim subreddit.

```viml
function! PvwExists()
    for winnum in range(1, winnr('$'))
        let l:pvwExists = getwinvar(winnum, '&previewwindow') ? winnum : 0
    endfor
    return l:pvwExists
endfunction

nnoremap <silent> <key-sequence> :exe PvwExists() ? 'pc' : 'GitGutterPreviewHunk'<CR>
```
I like toggles, hence I am now very pleased.

**Comment by airblade** [comment]
@bluz71 Thanks for posting your solution.

Wouldn't your function only work if the preview window were the last window?  I'd think this would be better:

```viml
function! PvwExists()
  for winnum in range(1, winnr('$'))
    if getwinvar(winnum, '&previewwindow')
      return 1
    endif
  endfor
  return 0
endfunction
```

**Comment by bluz71** [comment]
It seems to be the last window (from my testing).

**Comment by bluz71** [comment]
But, your version is safer, since my testing was only superficial.

**Comment by airblade** [comment]
I think for now it will always be the last window, but I plan to make that configurable soon (though it will still default to being the last).

Anyway, glad you got it doing what you wanted!

**Comment by bluz71** [comment]
Your enhanced version should be preferred.

I recommend adding the snippet to your FAQ, since some folks may like toggling behaviour.

Thanks for a superb plugin.
