### ISSUE TITLE
Starting takes a really long time?

### ISSUE THREAD

**Issue by RyanSquared** [airblade/vim-gitgutter#554]
> What is the latest commit SHA in your installed vim-gitgutter?

50a7062909d91a290fae04219887b1b45f3138db

> What vim/nvim version are you on?

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)

> If no signs are showing at all, what does `:echo b:gitgutter.path` give?

N/A

> If no signs are showing at all, and the `path` value is a path and not `-2`, does it work with `let g:gitgutter_grep=''`?

N/A

---

There's a noticeable length when starting Vim. It's like the plugin is taking a while to load. I can see that my colorscheme isn't taking affect until like a second after Vim starts. What can I do, if anything, to reduce the amount of time this plugin takes loading?

**Comment by airblade** [comment]
The best thing to do is [profile](https://github.com/airblade/vim-gitgutter/wiki/How-to-profile-vim-gitgutter) Vim's start up so we know exactly where the problem is.

However before you do that, you could try commenting out this line to see if that's the problem:

https://github.com/airblade/vim-gitgutter/blob/50a7062909d91a290fae04219887b1b45f3138db/autoload/gitgutter/diff.vim#L7

If it is, does the following take a long time too? `:echo system('ls')` or `:echo system('git status')`

**Comment by RyanSquared** [comment]
After some profiling, I've found that for some reason `vim-gitgutter` "hides" an issue I'm currently having with another plugin. I'm not sure as to why, but I think deoplete is to blame.

**Comment by RyanSquared** [comment]
(This also explains why it was only happening on `.rs` files instead of all files, as it was language-specific stuff that was crashing)

**Comment by airblade** [comment]
That's interesting.  Ok, let me know if vim-gitgutter could be changed so it doesn't hide the underlying problem, whatever it is.

**Comment by RyanSquared** [comment]
I don't think so. I think it comes down to the gutter being displayed post-start which might clear out the messages prompt? The messages prompt has always been weird with my setup, so I wouldn't say it's a definite bug, or even something that can/should be fixed, with gitgutter.

Closing due to this being not related.
