### ISSUE TITLE
Why does gitgutter depend on updatetime istead of events

### ISSUE THREAD

**Issue by astier** [airblade/vim-gitgutter#595]
Currently gitgutter updates the signs in a certain interval which is defined by the updatetime. Why is it time- and not event-based? The later seems to me to be more logical and also more efficient. For example it could depend on the events InsertLeave and TextChanged. This would update the signs only when changes have been made instead of every 100ms. This seems to me to be more efficient and also much more responsive to text-changes.

**Comment by airblade** [comment]
That's a good question.

The main driver of updates is `CursorHoldI` (and similarly `CursorHold`), which I think of as a debounced version of `TextChangedI` (and `TextChanged`).  (`TextChangedI` itself happens too often to trigger run a diff each time.)  The plugin only actually runs a diff if the buffer has changed since the last diff, so it's fairly efficient.

`InsertLeave` wouldn't give update signs until you left insert mode, whereas `CursorHoldI` updates more or less as soon as you pause your typing.

I feel that `CursorHoldI` is in fact event-based (if your `updatetim`e is sufficiently small, e.g. 100ms), and more efficient and responsive to text changes than `InsertLeave` would be.

**Comment by astier** [comment]
Thank you for the explanation. I agree on `InsertLeave`.
