### ISSUE TITLE
On terminal FocusGained, ordering of GitGutterAll and :checktime is wrong

### ISSUE THREAD

**Issue by RedBeard0531** [airblade/vim-gitgutter#607]
> What is the latest commit SHA in your installed vim-gitgutter?

7eeea63e62b1cc088a75c7a7c244fc774d82e5bb

> What vim/nvim version are you on?

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 22 2019 23:07:15)
Included patches: 1-996
```

If I have some changes and git stash, vim shows the new contents of the files but gitgutter keeps the old signs. It seems like it is trying to find the diffed lines using the old file contents, but doesn't use the new contents when they change. If I leave and reenter the terminal running vim again, it corrects itself, but it is annoying having to do the two-step dance.

This only seems to affect terminal vim (with wincent/terminus); gvim works fine. Setting `g:gitgutter_terminal_reports_focus = 0` doesn't help.

**Comment by airblade** [comment]
How are you doing the git-stash?

**Comment by RedBeard0531** [comment]
1. alt-tab to another terminal window
2. run `git stash`
3. alt-tab back to terminal running vim

**Comment by blueyed** [comment]
Is this a regression?  (I've wondered if it is related to 3d31383)
But that's probably a good start for debugging, i.e. add some `echom` for the related autocommand events.

**Comment by RedBeard0531** [comment]
@blueyed It wasn't that commit, I can repro before it. This seems like a vim/nvim difference. On nvim, at least with my config, the `FocusGained` autocmd seems unneeded, because the `FileChangedShellPost` autocmd seems to be sufficient.

For vim, I've found two workarounds:
1. have the `FocusGained` autocmd do something like `timer_start(500, {-> gitgutter#all(1) })`. It may be sufficient to have a very low timeout, like 1, just to deffer execution to the next "tick", but I didn't try getting that specific.
2. make the `FileChangedShellPost` autocmd run `gitgutter#all(1)`.

I couldn't figure out why the existing autocmds aren't working, but I'm neither a vimscript expert nor do I know my way around the gitgutter codebase. Hopefully for someone that is/does, those workarounds will point to an obvious solution. Or make it clear that there is actually an underlying bug in vim.

**Comment by airblade** [comment]
Hmm, I can't reproduce this with:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  7 2019 15:36:15)
macOS version
Included patches: 1-1099
Compiled by Homebrew
```

I have [terminus](https://github.com/wincent/terminus) installed.

With nvim 0.3.4 alt-tabbing back to the terminal after stashing doesn't update the file or the signs.

**Comment by airblade** [comment]
I've just tried this again and I can reproduce the problem on terminal MacVim though not GUI MacVim.

I added `echom` statements to the `FileChangedShellPost` and `FocusGained` autocommands; only the former seems to be executed.

Changing the `FileChangedShellPost` autocommand to run `gitgutter#all(1)` (as per your second suggestion) didn't solve the problem for me.  Which makes sense to me because all it does is call `gitgutter#process_buffer(bufnr(''), 1)` which is what the current handler does anyway.

I tried inserting a `checktime` call into the `FileChangedShellPost` autocommand but it didn't help, possibly because (according to the docs) vim postpones it until it would be "harmless", whatever that means.

The one thing that did work was delaying execution of `gitgutter#process_buffer(...)`, as per your first suggestion:

```diff
diff --git i/plugin/gitgutter.vim w/plugin/gitgutter.vim
index f5a212a..a8bad06 100644
--- i/plugin/gitgutter.vim
+++ w/plugin/gitgutter.vim
@@ -214,7 +214,7 @@ augroup gitgutter
   autocmd BufEnter * call s:on_bufenter()
 
   autocmd CursorHold,CursorHoldI * call gitgutter#process_buffer(bufnr(''), 0)
-  autocmd FileChangedShellPost   * call gitgutter#process_buffer(bufnr(''), 1)
+  autocmd FileChangedShellPost   * call timer_start(1, {-> gitgutter#process_buffer(bufnr(''), 1)})
 
   " Ensure that all buffers are processed when opening vim with multiple files, e.g.:
   "
```

Please could you try this patch and see whether it works for you?

**Comment by airblade** [comment]
The patch solves the problem for me so I'm assuming it solves the problem for you too.
