### ISSUE TITLE
Signs are color grey

### ISSUE THREAD

**Issue by plgrazon** [airblade/vim-gitgutter#614]
> What is the latest commit SHA in your installed vim-gitgutter?

commit e5936a22cfd2e25893e2ac34af4b0afdec1e36f5 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Wed May 15 16:27:17 2019 +0100

Fix tmux command.

> What vim/nvim version are you on?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 13 2019 17:42:00)
macOS version
Included patches: 1-900
Compiled by Homebrew
 
Signs are visible but they are color grey. I tried modifying the colors like stated on the docs but they're not working. I'm using desert as my colorsheme and iterm2 for my terminal

![Screenshot 2019-05-21 13 56 49](https://user-images.githubusercontent.com/33631935/58130188-515d6500-7bd0-11e9-8846-ebb85b91a27d.png)

**Comment by airblade** [comment]
This is probably due to changes made in faa1e95...3ce2a4b: previously the plugin set its own colour values for the signs; those changes made the plugin use colours from the colorscheme instead.  In theory this should work better across colorschemes but in practice it has caused a bit of trouble.

I'll try to reproduce this with your colorscheme...

**Comment by plgrazon** [comment]
" Git Gutter"
 set updatetime=250
 let g:gitgutter_max_signs = 500
 " No mapping
 let g:gitgutter_map_keys = 0
 " Colors
 let g:gitgutter_override_sign_column_highlight = 0
 highlight clear SignColumn
 highlight GitGutterAdd    ctermfg=2
 highlight GitGutterChange ctermfg=3
 highlight GitGutterDelete ctermfg=1
 highlight GitGutterChangeDelete ctermfg=4

**Comment by JPFrancoia** [comment]
This fixed my issue too but it'd be nice to know why we have to specify numbers instead of the colours names

**Comment by airblade** [comment]
I don't know either why the colour names don't work.

**Comment by adah1972** [comment]
Currently with HEAD I am getting black on dark grey with [my colour scheme](https://github.com/mbbill/desertEx). Commit faa1e95 has much better default colours.

My test shows changing `highlight GitGutterAdd…` in .vimrc has no effect. Doing it after a file is loaded is OK… Sad. Do I have to to modify the colour scheme files? It won’t work well on system default schemes, if I want to change the gitgutter colours for them.

I am on MacVim 162 (Vim 8.2.319).

**Comment by adah1972** [comment]
I see the problem. The desertEx scheme has:

```
highlight DiffAdd guifg=black guibg=wheat1
highlight DiffChange guifg=black guibg=skyblue1
highlight DiffDelete guifg=black guibg=gray45 gui=none
```

It differentiates the diff stuff by background colours! This is not the way vim-gitgutter does things. The problem is that this is common enough—in fact, all three colour schemes I use daily do not change the foreground colours for diff.

It seems to me vim-gitgutter had better use an alternative method to decide colours. I would recommend revert to the original colours, with variables to allow changing colours.

**Comment by airblade** [comment]
> It seems to me vim-gitgutter had better use an alternative method to decide colours. I would recommend revert to the original colours, with variables to allow changing colours.

As you say, vim-gitgutter used to set default colours for the signs.  But the point of colour schemes is that the colour scheme chooses the colours – which is why I changed the plugin to use the colour scheme's colours defined (while still allowing people to set their own colours).  This still seems reasonable to me.

It turns out, though, that a number of colour schemes have diff colours that people don't like.  In this case you can either change the colour scheme or set your own colours in your vimrc.

It comes down to: either vim-gitgutter chooses default diff colours which you can override; or your colour scheme chooses default diff colours which you can override.  I think the latter makes more sense.

**Comment by adah1972** [comment]
> It turns out, though, that a number of colour schemes have diff colours that people don't like. In this case you can either change the colour scheme or set your own colours in your vimrc.

This is not completely true. First, the colour schemes themselves are OK, as they use background colours to differentiate—they are not to blame. Second, as I mentioned, it could be that neither can I change the colour scheme (system schemes), nor can I change it in .vimrc (currently it has no effect, because of the load order).

> It comes down to: either vim-gitgutter chooses default diff colours which you can override; or your colour scheme chooses default diff colours which you can override. I think the latter makes more sense.

Letting people choose is a good idea, but letting the colour scheme choose is not a good idea to me. People normally do not edit colour schemes themselves. The major problem is that **the default values are bad**—many people can get the bad signs on first use, or on update. It *is* discouraging.

I first decided to downgrade when encountering the problem. Only after quite a few days did I have time to investigate further.

The solution to me seems to be:

- Make the default value work again—that is, ensure good colours under most colour schemes the users happen to use. Currently the default git-gutter colours do not work with *default* schemes!
- Allow people to choose alternative colours with variables: it could be a `gitgutter_use_scheme_diff_color` (default to 0) along with `gitgutter_color_add` etc.

**Comment by adah1972** [comment]
I have proposed a PR https://github.com/airblade/vim-gitgutter/pull/684.

If you agree with the direction, I can add some documentation too.

**Comment by adah1972** [comment]
@airblade Hi Andy, would you please look at the issue again and my PR?

I came here because I am writing a tutorial of Vim, and I really want to recommend vim-gitgutter. However, given the current status, ***the colours are pretty bad out of the box***. It has problems in my configuration, and it has problems in all the default colour schemes, on Linux or on macOS.

You cannot blame the default colour schemes that they do not support vim-gitgutter well… And making a plugin work well without extra configurations would be very helpful to new users.

**Comment by airblade** [comment]
You seem to be implying that the plugin deliberately chooses bad colours.  On the contrary: it doesn't have an opinion on colours.  Originally it defined default colours but I changed that because of the number of people who complained the defaults didn't work well with their preferred colour schemes – they didn't want to figure out the colour values they wanted and change the defaults to those; they just wanted gitgutter to use their colour scheme.

**Comment by airblade** [comment]
> My test shows changing highlight GitGutterAdd… in .vimrc has no effect.

That's odd.  It should work.  When the plugin loads it will see those highlight groups and not overwrite them.

**Comment by adah1972** [comment]
> You seem to be implying that the plugin deliberately chooses bad colours. On the contrary: it doesn't have an opinion on colours. Originally it defined default colours but I changed that because of the number of people who complained the defaults didn't work well with their preferred colour schemes …

A better summary is this: Your current code works better with colour schemes that have ‘suitable’ Diff colours, but it does not work well with some other colour schemes, like the *default* ones. I personally believe making things work under the default settings is important. So My PR is trying to achieve something in the middle:

- As it is: It works very well with default colour schemes, perhaps less so with users with special colour schemes. Since they tend to be advanced users that can find information quickly in the doc, they will find out `g:gitgutter_use_colorscheme` in a few minutes.
- Make `g:gitgutter_use_colorscheme` default to 1: The GitGutter behaviour is basically unchanged, but there will be an option to make it work better on colour schemes that do not have suitable Diff… highlights.
- What ever the value of `g:gitgutter_use_colorscheme` is, custom hightlights like GitGutterAdd will always work (except in some corner cases on Mac).

**Comment by airblade** [comment]
I haven't forgotten about this.  All my coding time is taken up with work at the moment; when I have some time available again I will come back to this.

**Comment by airblade** [comment]
I have just amended the way the plugin sets the signs' colours (8db2fc5).  From the docs:

> If you or your colourscheme has defined `GitGutter*` highlight groups, the plugin will use those for the signs' colours.
>
> Otherwise it will use your colourscheme's `Diff*` highlight groups.
>
> Either way the signs' background colours will be set to the sign column's background colour.
>
> If you don't like the colours, specify the ones you want in your vimrc (see `:help highlight-guifg` and `:help highlight-ctermfg`).  For example, to get vim-gitgutter's original colours (based on git-diff's colours in my terminal):
>
> ```viml
> highlight GitGutterAdd    guifg=#009900 ctermfg=2
> highlight GitGutterChange guifg=#bbbb00 ctermfg=3
> highlight GitGutterDelete guifg=#ff2222 ctermfg=1
> ```

Previously if the user wanted to change the signs' colours they had to also figure out what background to specify, which was an unnecessary obstacle.

[Earlier](https://github.com/airblade/vim-gitgutter/issues/614#issuecomment-600715521) you wrote:

> all three colour schemes I use daily do not change the foreground colours for diff.

That's still going to be a problem, I'm afraid.  The solution is to copy-paste the three-line snippet from the docs.

I agree that making things work well by default is good.  However there's no way for the plugin to distinguish colour schemes that set good diff colours from those that don't, so if I make people have to opt in to use their colour scheme's colours, that breaks the default for them.  And although the built-in colour schemes don't seem to work well, I believe more people install and use a non-built-in one than use a built-in one – and most non built-in colour schemes do define good GitGutter or diff colours.

**Comment by adah1972** [comment]
Is there not a common background to make this plugin work well with colour schemes tailored for GitGutter and those that are not?

The colour scheme I use most often is desertEx, which does define its own Diff… colours. It is just that those colours are really for diff purposes, not for GitGutter. They work very well for Diff, but not for GitGutter.

The same holds true for default colour schemes.

**Comment by airblade** [comment]
I still believe the majority of colour schemes in use do define colours which work well for signs.

Anyway, how about this: if no GitGutter* highlights are defined, and Diff* ones are, but the Diff* ones all have the same foreground colour, the plugin ignores the Diff* colours and sets up default green / red / etc instead.

**Comment by adah1972** [comment]
That may solve the problem. My sole purpose is make it work out of the box without extra configurations.

**Comment by airblade** [comment]
> My sole purpose is make it work out of the box without extra configurations.

That is not apparent.

**Comment by airblade** [comment]
Done in f458f43.
