### ISSUE TITLE
vim-fugitive integration

### ISSUE THREAD

**Issue by pwsiegel** [airblade/vim-gitgutter#666]
> What is the latest commit SHA in your installed vim-gitgutter?
af20a9fcfff9b5277fc8482e802c4dec291ea589

> What vim/nvim version are you on?
Vim 8.1

First of all: this is a great plugin, and thanks for all the hard work!  I just started using it, and it's already life changing - I don't encounter too many new plugins that meet that standard anymore.

I use this along with the tpope plugin `vim-fugitive` (I'm sure I'm not alone), and my wish is that this plugin were aware of what I had done with that one.  Specifically: if I stage or unstage changes in `vim-fugitive`'s `:Gstatus` interface, I would like `vim-gitgutter` to update the gutter symbols accordingly.  I don't know much about the inner workings of either plugin and so I can't be sure how feasible this is, but I am envisioning this plugin listening for some sort of `onClose` event triggered by the `:Gstatus` window or something.

And of course if there is a known workaround which I can add to my vimrc, I'm happy to do that.

**Comment by airblade** [comment]
I'm glad to hear the plugin is helpful.

This came up most recently in #502 which resulted in e608bff4 based on https://github.com/tpope/vim-fugitive/issues/503#issuecomment-521436738.

I'm not sure what else I could do but let me know if you think of anything.

**Comment by thisisrandy** [comment]
I wonder if it would be overly expensive/otherwise problematic to do your refresh operation on window enter? The problem here seems to go both ways: If I stage a hunk with gitgutter and fugitive is open in a split, fugitive doesn't see it, and if I stage a file with fugitive, gitgutter doesn't see it. However, fugitive's behavior is still kind of reasonable, because if I type `:Gstatus` again (rather than just moving back to the open split), it triggers a refresh, and I'm almost never going to be leaving fugitive open in a split, anyhow. It seems like the common workflow would be:

1. (Un)stage in fugitive
2. Possibly commit
3. Close fugitive OR navigate out of split

In either case, there's an opportunity to trigger an update as soon as the fugitive window is exited, which is a pretty close approximation to updating anytime there's a change.

If it's unclear, what I mean is essentially to bake in `autocmd WinEnter * :GitGutterAll`. How does that sound?

**Comment by airblade** [comment]
> ...what I mean is essentially to bake in `autocmd WinEnter * :GitGutterAll`. 

Well that would make the plugin do unnecessary work for everyone, while only potentially benefitting people who use Fugitive.

Alternatively, you could try this in your vimrc:

```viml
autocmd BufLeave fugitive://* call gitgutter#all(1)
```

I'm not sure what the best pattern would be in the autocmd because I don't use Fugitive.

**Comment by thisisrandy** [comment]
That's an excellent idea, but unfortunately I'm having trouble figuring out the appropriate pattern. In the fugitive window, I have
```
:echo @%
(...)/.git/index
:echo &ft
fugitive
```
Is there some magic that I can use to match on file type?

> Well that would make the plugin do unnecessary work for everyone, while only potentially benefitting people who use Fugitive.

Point taken. Perhaps as a compromise (once we get the autocmd right), would you consider putting it in your readme under "vim-fugitive compatibility" or some such?

**Comment by thisisrandy** [comment]
I'll note that 
```vim
autocmd BufLeave */.git/index call gitgutter#all(1)
```
works, but a file type-based pattern would feel cleaner if possible.

**Comment by airblade** [comment]
You'll have to ask in the Fugitive repo what the best pattern would be.

Ideally I'd want the signs to update when Fugitive does something that changes the git index, i.e. stages or unstages something, without the user having to leave the buffer.
