### ISSUE TITLE
When a fugitive buffer is open, gitgutter gets out of sync

### ISSUE THREAD

**Issue by wookayin** [airblade/vim-gitgutter#695]
> What is the latest commit SHA in your installed vim-gitgutter?

5f6048d (latest as of 2020. 4. 14.)

> What vim/nvim version are you on?

Neovim 0.4.3 and nightly (NVIM v0.5.0-439-gfb4c7a53c)

### \1. Set up with a minimal vimrc
```
❯❯❯ nvim -u <(cat <<EOF
set rtp+=~/.vim/plugged/vim-fugitive/
set rtp+=~/.vim/plugged/vim-gitgutter/
source ~/.vim/plugged/vim-fugitive/plugin/fugitive.vim
source ~/.vim/plugged/vim-gitgutter/plugin/gitgutter.vim
map ,ha <Plug>(GitGutterStageHunk)
EOF
)
```

Open any file under a git repository.

### \2. Open fugitive buffers

```
:e vim/vimrc       " an example file
:Gvdiffsplit HEAD
:wincmd p
:Gvdiffsplit
```

### \3. Try add a hunk

Press `,ha` to do stage a hunk.

- Expected: If everything is good, the hunk should be added to the index and the gitgutter sign should disappear.
- Actual: The gitgutter sign does not disappear. But the lines are added to the index. If you do `,ha` multiple times, these lines will be added to index **multiple time** (duplicated lines).

Note: Somehow vim-fugitive does not refresh its buffer when index buffer is open but the stage area is actually changed. This might be a bug of vim-fugitive, but vim-gitgutter also gets out of sync. Invoking `:call gitgutter#all(1)` does not help at all.

**Comment by airblade** [comment]
After step 2, I have three buffers:

```
fugitive:///path/to/vim/.git//<sha>/vimrc
fugitive:///path/to/vim/.git//0/vimrc
vimrc
```

The cursor is in the middle one.  However I presume your cursor is in the third because that's the only one which shows signs.  (The plugin is designed to work with files in the working tree.)

Anyway, I get the same erroneous behaviour as you: staging a hunk updates the index (confirmed by `git diff --staged` in another terminal window) but not the signs.  I wonder if it's because the buffer is in a diff window (i.e. `&diff` is on).

I'll investigate further.

**Comment by airblade** [comment]
Forgot to say: thank you for the clear repro steps.

**Comment by airblade** [comment]
I'm pretty sure this is due to 0e509fb.  The previous version of the file loaded up by `:Gvdiffsplit HEAD` causes vim-gitgutter to set the (global) diff base to the parent of that commit.  Then when you stage a hunk in the working-tree file, and the plugin recalculates the signs, it uses the global diff base which is still the parent of the commit – so the signs stay the same.

**Comment by wookayin** [comment]
Yes I forgot to say we adding hunk is for the editable (normal) buffer for the file. It's so great you figured out the reason of the bug so quickly, and it now works well! Thank you :)

**Comment by wookayin** [comment]
Another small inconvenience is that the added hunk does not reflected in the fugitive index buffer. I believe fugitive is primarily responsible for this (https://github.com/tpope/vim-fugitive/issues/1517), but as this plugin is aware of vim-fugitive it might also be a good idea for gitgutter to trigger fugitive buffers to refresh. Do you think it is something gitgutter can work around?

**Comment by airblade** [comment]
If Fugitive doesn't automatically refresh its view of a staged file when the index is updated, that's Fugitive's business, not vim-gitgutter's.

However I'm happy to try to make things easier if possible.  Maybe vim-gitgutter could fire a User autocmd when it updates the index; you could listen for that event and refresh any Fugitive buffers which may be open.  Would that help?

**Comment by wookayin** [comment]
Thanks @airblade. Yeah, it's a shame that fugitive is not supportive of *such a very obvious* feature. I've opened a new feature request #698. This issue is well fixed and done!
