### ISSUE TITLE
Can't open file for writing: Error processing gitgutter#diff#run_diff

### ISSUE THREAD

**Issue by Nitrodist** [airblade/vim-gitgutter#746]
After switching branches and/or working in a branch for a bit I encounter an error in :messages everytime I type a character - I have to quit and start vim again to fix it. 

It has something to do with what looks like a temporary directory no longer existing, it seems at first glance. Any advice?

> What is the latest commit SHA in your installed vim-gitgutter?

```
commit 987a33355ef424161fdbc4e5d625b5b5aed9704c (HEAD -> master, origin/master, origin/HEAD)
Author: obcat <obcat@icloud.com>
Date:   Mon Nov 2 01:44:35 2020 +0900

    Show message like "Hunk 4 of 11" after hunk jumping
```

> What vim/nvim version are you on?

nvim v0.4.3

![image](https://user-images.githubusercontent.com/385448/98400032-fd934580-2028-11eb-9de0-b4c1c145df06.png)

```
Error detected while processing function gitgutter#process_buffer[19]..gitgutter#diff#run_diff[38]..<SNR>92_write_buffer:
line   27:
E482: Can't open file /var/folders/px/5xltrff14p36zxld0qx6klz80000gn/T/nvimdWNG4N/35.1.17 for writing: no such file or directory

```

**Comment by airblade** [comment]
This happens occasionally because vim/neovim has been open for several days and the OS has deleted the temp directory from under vim.

The plugin could catch the error but there's nothing it can really do about it – it already asks vim for [fresh temp files](https://github.com/airblade/vim-gitgutter/blob/987a33355ef424161fdbc4e5d625b5b5aed9704c/autoload/gitgutter/diff.vim#L78-L79) every time it runs a diff.  I would expect vim to ask the OS for fresh temp files each time but maybe it doesn't.

**Comment by airblade** [comment]
How long has your vim/neovim been open for when you start to get these errors?

**Comment by airblade** [comment]
As far as I can tell Vim creates a [temp directory once for its own use](https://github.com/vim/vim/blob/bbf9f344afd08954163191ed678352fb554fc254/src/fileio.c#L5060) and then creates files inside it every time it needs a temp file.

So if the OS deletes that temp directory, Vim will no longer be able to create temp files.

The only way around this would be for the plugin to manage its own temp directories and temp files, but I feel that's out of scope.  It would be better for this to be fixed in Vim itself.

**Comment by Nitrodist** [comment]
I constantly close and open my vim. I rarely have it open an entire day. This is a problem that cropped up only recently with your plugin and it was pretty insistent.

**Comment by airblade** [comment]
Oh, ok.

Nothing has changed recently with the part of the plugin that writes temp files.  Have you upgraded vim-gitgutter recently?  If so, and you can find the commit it was on (should be available via git-reflog), perhaps you could git-bisect to identify when the problem was introduced.

Or have you upgrade nvim recently?

**Comment by davidwales** [comment]
I've just started getting this in nvim. Strangely, I haven't updated nvim or my plugins for some time. It happened again less than 5 minutes after re-launching nvim.

**Comment by airblade** [comment]
@davidwales Thanks for the info.  Which commit is your vim-gitgutter at?

**Comment by davidwales** [comment]
`git log` says:

``` git
commit 8005f71aabef13f5872b3ef4802f36503a16c451 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Andy Stewart <boss@airbladesoftware.com>
Date:   Fri Aug 7 12:06:17 2020 +0100

    Avoid floating preview window immediately closing itself

    Fixes #728.
```

I'm running on Windows 10, 1909.

**Comment by airblade** [comment]
@Nitrodist @davidwales Does this patch solve the problem for you?

```diff
diff --git i/autoload/gitgutter/diff.vim w/autoload/gitgutter/diff.vim
index 0644a8e..5f55e7d 100644
--- i/autoload/gitgutter/diff.vim
+++ w/autoload/gitgutter/diff.vim
@@ -400,7 +400,16 @@ function! s:write_buffer(bufnr, file)
     let bufcontents[0]='﻿'.bufcontents[0]
   endif
 
-  call writefile(bufcontents, a:file, 'b')
+  " The file we are writing to is a temporary file.  Sometimes the parent
+  " directory is deleted outside Vim but, because Vim caches the directory
+  " name at startup and does not check for its existence subsequently, Vim
+  " does not realise.  This causes E482 errors.
+  try
+    call writefile(bufcontents, a:file, 'b')
+  catch /E482/
+    call mkdir(fnamemodify(a:file, ':h'), '', '0700')
+    call writefile(bufcontents, a:file, 'b')
+  endtry
 endfunction

 ```

**Comment by davidwales** [comment]
That works! Before applying the patch, manually deleting the temp directory raised an error.
After the patch, I can delete the temp directory without seeing any errors. (And the gitgutter keeps working!)

**Comment by airblade** [comment]
Thanks for confirming – that's good news.
