### ISSUE TITLE
Random E903 errors

### ISSUE THREAD

**Issue by mosheavni** [airblade/vim-gitgutter#770]
> What is the latest commit SHA in your installed vim-gitgutter?
1283ec1670d1f4fce37213c5d66924088b2e730c

> What vim/nvim version are you on?
NVIM v0.4.4

Getting those weird errors, have no idea how to reproduce:
![image](https://user-images.githubusercontent.com/17252601/109837501-ea4a5c80-7c4d-11eb-90c2-ed53fbde7ccf.png)

**Comment by airblade** [comment]
Please read the discussion in #767 and see if it helps.

**Comment by mosheavni** [comment]
> Please read the discussion in #767 and see if it helps.
> […](#)
> On 3 Mar 2021, at 16:26, Moshe Avni ***@***.***> wrote: ﻿ What is the latest commit SHA in your installed vim-gitgutter? [1283ec1](https://github.com/airblade/vim-gitgutter/commit/1283ec1670d1f4fce37213c5d66924088b2e730c) What vim/nvim version are you on? NVIM v0.4.4 Getting those weird errors, have no idea how to reproduce: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

read it, there's no actual solution there.

**Comment by airblade** [comment]
Well there are some things to investigate:

- Is your `'updatetime'` below 50ms?
- Can you reproduce the problem with only vim-gitgutter?
- If not, have you done a binary search on your plugins to pinpoint which in conjunction with this one causes the errors?  (You could cross-reference them with [these](https://github.com/airblade/vim-gitgutter/issues/767#issuecomment-785229181) and see if you have any in common.)

I believe the cause is another plugin misbehaving, either using up lots of file descriptors itself or continually flicking between buffers every few milliseconds.

**Comment by airblade** [comment]
Any progress?

**Comment by mosheavni** [comment]
> Any progress?

Haven't returned! thanks.
