### ISSUE TITLE
Bug & suggestion for g:gitgutter_close_preview_on_escape option

### ISSUE THREAD

**Issue by bew** [airblade/vim-gitgutter#784]
Plugin version: f4bdaa4e9cf07f62ce1161a3d0ff70c8aad25bc5 (current master)
Neovim version: v0.4.3

When setting the option
```vim
let g:gitgutter_close_preview_on_escape = v:true
```
There is now an `<esc>` mapping 'owned' by gitgutter (mapped to one of its function).

2 things:
1. BUG: when doing `42<esc>` (`42`: as if I was trying to start a range action, `<esc>` to cancel it), the cursor moves unexpectedly.
2. The `<esc>` key is _really_ important, and I'd prefer to not have it always mapped to a plugin' function.
   Could you expose a function to close the preview window? (that I could call myself with `<esc>` or another binding)
   The suggested commands (`Ctrl-w Ctrl-z` & `:pclose` do not work when the preview is in a floating window)

**Comment by airblade** [comment]
1. That's how normal-mode maps work.
2. I agree `<esc>` is important; that's why close-preview-on-escape is off by default.

I wrote the documentation on how to close a hunk preview when non-floating previews were the only kind of hunk preview.  Looking at it now I can see how it needs updating – which I have done in ba21c56.

Given the updated docs, do you still want a function you can call to close a floating hunk preview?

**Comment by bew** [comment]
Thanks for the documentation update :+1: 

For 1. I don't agree, with this diff you can make the cursor not move in this case!
```diff
diff --git a/autoload/gitgutter/hunk.vim b/autoload/gitgutter/hunk.vim
index f530e3e..4527fea 100644
--- a/autoload/gitgutter/hunk.vim
+++ b/autoload/gitgutter/hunk.vim
@@ -448,7 +448,7 @@ function! s:open_hunk_preview_window()
       " Assumes cursor is in original window.
       autocmd CursorMoved <buffer> ++once call s:close_hunk_preview_window()
       if g:gitgutter_close_preview_on_escape
-        nnoremap <buffer> <silent> <Esc> :call <SID>close_hunk_preview_window()<CR>
+        nnoremap <buffer> <silent> <Esc> :<C-u>call <SID>close_hunk_preview_window()<CR>
       endif

       return
```
This is because `42:` inserts `:.,.+41` in the cmdline!
An alternative that works on neovim is to use `map ... <cmd>call <SID>close_hunk_preview_window()<CR>
`
But it's not generally available in vim afaik..

> Given the updated docs, do you still want a function you can call to close a floating hunk preview?

Actually yes, because I like the escape to close popup, but would like to control this mapping myself.

I check the code, and would like to apply this diff (in addition to the last one, even if I won't use it):
```diff
diff --git a/autoload/gitgutter/hunk.vim b/autoload/gitgutter/hunk.vim
index f530e3e..a4b5fac 100644
--- a/autoload/gitgutter/hunk.vim
+++ b/autoload/gitgutter/hunk.vim
@@ -600,13 +600,25 @@ function! s:close_hunk_preview_window()
   let s:preview_bufnr = 0
 endfunction

+function! gitgutter#hunk#close_hunk_preview_window()
+  call s:close_hunk_preview_window()
+endf

-" Only makes sense for traditional, non-floating preview window.
 function s:is_preview_window_open()
+  if g:gitgutter_preview_win_floating
+    if win_id2win(s:winid) > 0
+      return 1
+    endif
+  else
     for i in range(1, winnr('$'))
       if getwinvar(i, '&previewwindow')
         return 1
       endif
     endfor
+  endif
   return 0
 endfunction
+
+function! gitgutter#hunk#is_preview_window_open()
+  return s:is_preview_window_open()
+endf
```
I'm using wrappers here, just to not have to rewrite the call sites of the functions, but if you're ok with this I can make a PR (renaming the functions, not making wrappers).

**Comment by airblade** [comment]
1.  I'm happy for you to add `<C-U>` as per your diff.  I normally include that in maps but evidently I forgot here.

I still don't really get where and when your cursor is moving.  Are you typing `42<esc>` while a floating hunk preview is open or after you have closed it?

It would be better if the [map were once-only, like the autocmd](https://github.com/airblade/vim-gitgutter/blob/10998f303cd85405e51380f6dc406dd756c105e8/autoload/gitgutter/hunk.vim#L449-L452), but AFAIK Vim doesn't support that.

Thanks for the tip about `<Cmd>`, of which I wasn't aware.  It looks pretty helpful but we can't use it here because it was added in Vim 8.2.1978 / Neovim 0.3.0 and would break backward compatibility.

2.  That change looks good to me, renaming the functions to make them public instead of using wrappers.  Please could you also document the newly-public function in the plugin's help doc?  I don't think it's necessary to add any tests.

**Comment by bew** [comment]
> I still don't really get where and when your cursor is moving. Are you typing `42<esc>` while a floating hunk preview is open or after you have closed it?

When I open a file, any file, open a hunk preview (to have that mapping set) and close it, then:
Typing `3<esc>` will move the cursor down by 2 lines.

**Comment by airblade** [comment]
Thanks for clarifying.

**Comment by bew** [comment]
>     1. Please could you also document the newly-public function in the plugin's help doc?

I've never written documentation for a vim plugin, is there a preference as to where I document this in the doc/gitgutter.txt ?

Do I just mention the 2 functions next to the option? Or make a new section for functions?

**Comment by airblade** [comment]
I think mentioning `gitgutter#hunk#close_hunk_preview_window()` at the end of the docs for `GitGutterPreviewHunk`, after the sentence about `g:gitgutter_close_preview_on_escape`, would suffice.

**Comment by airblade** [comment]
By the way, why do want to make the `is_preview_window_open()` function public?

**Comment by bew** [comment]
> By the way, why do want to make the `is_preview_window_open()` function public?

Basically to make the mapping aware of this, and allow me to do something different when the preview is not open.
_The keyboard doesn't have infinite keys! let's reuse them!_

**Comment by bew** [comment]
Ah yes well ok, good, now it's done ^^
Sorry didn't took the time to finish this properly
