### ISSUE TITLE
Using signcolumn=number breaks linenumber highlights

### ISSUE THREAD

**Issue by dob9601** [airblade/vim-gitgutter#804]
> What is the latest commit SHA in your installed vim-gitgutter?
256702dd1432894b3607d3de6cd660863b331818
> What vim/nvim version are you on?
NVIM v0.6.0-dev+227-gc1f573fbc

Using:
```
let g:gitgutter_signs=0
let g:gitgutter_highlight_linenrs=1
highlight GitGutterAddLineNr guifg=lightgreen
highlight GitGutterChangeLineNr guifg=lightblue
highlight GitGutterDeleteLineNr guifg=lightred
highlight GitGutterChangeDeleteLineNr guifg=lightred
```

works in terms of showing colours (but not symbols) for changes until

```
set signcolumn=number
```
is used, at which point all line numbers disappear

**Comment by airblade** [comment]
Hmm, when I use the config above I still see the symbols (+,-,~).  That's unexpected, and also different from what you report.

When I apply `set signcolumn=number` the sign column disappears and the line numbers of the lines with signs are replaced by the signs; the other line numbers remain intact.  Which is what I would expect.

So it seems I can't reproduce either behaviour.  I'll keep looking into this.

I'm using NVIM v0.6.0-dev+1478-gd791274a9 which is close to your version.

**Comment by airblade** [comment]
Ah, I can reproduce everything you report when I specify a colorscheme.  My config was so minimal that it didn't specify a colorscheme, only a dark background, and for some reason that changed how things behaved.

Anyway, the line numbers disappear because they are replaced with signs (symbols) which are drawn with the signs' (i.e. symbols') highlights.  And the symbols are invisible due to `let g:gitgutter_signs=0`.

If you want to be able to `set signcolumn=number` then remove `let g:gitgutter_signs=0` and add these highlights:

```
highlight GitGutterAdd guifg=lightgreen
highlight GitGutterChange guifg=lightblue
highlight GitGutterDelete guifg=lightred
highlight GitGutterChangeDelete guifg=lightred
```
