### ISSUE TITLE
Neovim now prefers extmarks to signs

### ISSUE THREAD

**Issue by airblade** [airblade/vim-gitgutter#876]
https://github.com/neovim/neovim/pull/25724

**Comment by luukvbaal** [comment]
There is no need to rush to use the extmark API instead of the `:sign` commands (I doubt they will ever be deprecated). The point of https://github.com/neovim/neovim/pull/25724 was to make sure that neovim uses extmarks internally to display signs placed using the `:sign` commands.

If you're making a neovim only plugin sure, the extmark API may be preferred. But I wouldn't bother maintaining both a `:sign` and extmark implementation :)

**Comment by airblade** [comment]
Thanks for the info, I appreciate it.

It seems clear that the `:sign` commands are regarded as legacy, so it wouldn't surprise me if sooner or later they were dropped.  Even if they aren't, I'd prefer to use the recommended API.

As for maintaining both a `:sign` and extmark implementation, vim-gitgutter maintains compatibility with old / legacy APIs back to Vim 7.4 while using newer APIs if available.  Backwards compatibility is tedious though :)

**Comment by airblade** [comment]
On second thoughts I'll follow your advice and leave this for now.
