### ISSUE TITLE
Plugin doesn't work with old version git.

### ISSUE THREAD

**Issue by sheer-rey** [airblade/vim-gitgutter#900]
I installed the newest commit of gitgutter plugin, and found it doesn't work in my old centos7.6 environment.

I have try to find out the reason, that is, after the commit _bed580a_, gitgutter plugin use `git -C` instead of `cd` to work with git repositories, but there's no `-C` option in old version git.

![image](https://github.com/user-attachments/assets/86e96880-6d57-4891-98f4-0e6c5e9fa2a1)

So, is there any probability to keep this plugin compatible with the old version git?

Best Regards!

**Comment by airblade** [comment]
Thanks for taking the time to identify the problem!

I do try to keep backwards compatibility as much as possible, but `-C` was added to git in [v1.8.5](https://github.com/git/git/blob/76cf4f61c87855ebf0784b88aaf737d6b09f504b/Documentation/RelNotes/1.8.5.txt) in December 2013.  Using `git -C <dir> ...` instead of `cd <dir> && git ...` simplifies the plugin code, and I think dropping compatibility with something 12 years old is a good trade-off.  Sorry!
